foreground   #c1ced0
background   #090b0f
cursor       #c1ced0

color0       #090b0f
color8       #879091
color1       #3D5962
color9       #3D5962
color2       #4C646C
color10      #4C646C
color3       #B63F3F
color11      #B63F3F
color4       #607C82
color12      #607C82
color5       #718E92
color13      #718E92
color6       #6FC3CA
color14      #6FC3CA
color7       #c1ced0
color15      #c1ced0
